### ISSUE TITLE
Cant get the zones to work

### ISSUE THREAD

**Issue by HeadhunterEcho** [StalkR/Space-Engineers-Asteroid-Ores#1] opened 2023-10-01 00:14 UTC
Hello, I have been trying to get this to work for the past 5 hours. 
I can get the plugin to remove all the asteroids in the world, but anytime I add a zone to the config, it doesnt work and then resets itself. 

Im using it on a dedicated server from GTX, using torch. I dont really know what im doing wrong at this point. Any help would be appreciated.

**Comment by StalkR** [comment] 2023-10-01 01:29
Hello, sorry to hear that.

Can you share the config you're trying to use and doesn't work? Maybe I can
spot what's wrong.

Also describe what you'd like and I can checi that's what the config does
or write the config.

Cheers

**Comment by StalkR** [comment] 2024-01-02 08:11
Note: the config file resetting itself to empty could be caused by an invalid xml syntax. If you share the config you tried I can tell you what's the issue.

Closing this as it's been over 3 months.

**Closed as completed by StalkR** 2024-01-02 08:11 UTC
