### ISSUE TITLE
Not generating

### ISSUE THREAD

**Issue by Karmaknight421** [StalkR/Space-Engineers-Asteroid-Ores#2] opened 2023-11-23 02:59 UTC
I copied your code exactly just to get an idea of how to set things up, it caused asteroids to be like a hologram, I could go right through them. It also did not spawn a belt around <0> <0> <0>. The plugin seems to be broken

**Comment by Karmaknight421** [comment] 2023-11-23 05:57
<?xml version="1.0" encoding="utf-8"?>
<Config xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  
  <AllOres>false</AllOres>
  <Ores />

  <Zones>

    
    <Zone>
      <AllOres>false</AllOres>
      <Ores>
        <string>Cobalt</string>
        <string>Gold</string>
        <string>Ice</string>
        <string>Iron</string>
        <string>Magnesium</string>
        <string>Nickel</string>
        <string>Stone</string>
        <string>Silicon</string>
        <string>Silver</string>
        <string>Uranium</string>
      </Ores>
      <Center>
        <X>0</X>
        <Y>0</Y>
        <Z>0</Z>
      </Center>
      <MaxRadius>130000</MaxRadius>
      <MinRadius>80000</MinRadius>
      <Height>10000</Height>
    </Zone>

    
    <Zone>
      <AllOres>true</AllOres>
      <Ores />
      <Center>
        <X>1000000</X>
        <Y>1000000</Y>
        <Z>1000000</Z>
      </Center>
      <MaxRadius>100000</MaxRadius>
    </Zone>

  </Zones>
</Config>

I copy pasted this directly into the asteroidOres.cfg

**Comment by StalkR** [comment] 2023-11-23 14:19
Hey, I'll take a look see if I can reproduce, and add more logging. Someone else couldn't make it work in #1.

I have it working on a server so it seems fine to me.

By the way, are you using spectator mode to fly around? I noticed a bit of a bug with spectator, since the game doesn't load asteroids in spectator but only when the player is teleported, and the client side mod only deletes when camera is back to the player instead of spectator. Best way to be sure you're not hitting this sort of issue is to fly around as admin in spectator, then quit game entirely, launch it again and reconnect - ensures a clean, fresh state. I'm tracking this bug in #3 and will work on it whenever I have time.

**Comment by Karmaknight421** [comment] 2023-11-23 20:16
> Hey, I'll take a look see if I can reproduce, and add more logging. Someone else couldn't make it work in #1.
> 
> I have it working on a server so it seems fine to me.
> 
> By the way, are you using spectator mode to fly around? I noticed a bit of a bug with spectator, since the game doesn't load asteroids in spectator but only when the player is teleported, and the client side mod only deletes when camera is back to the player instead of spectator. Best way to be sure you're not hitting this sort of issue is to fly around as admin in spectator, then quit game entirely, launch it again and reconnect - ensures a clean, fresh state. I'm tracking this bug in #3 and will work on it whenever I have time.

I appreciate the quick reply! 
I have been flying around in suit and been able to phase through asteroids, I moved my camera to a different area, teleported my body there and then tried to fly into the newly generated asteroids and was able to phase through them as well. However, at one point near one of the planets that was meant to have a ring around it I did crash into an asteroid with a ship (the ship phased right through about 10 before colliding with a real one)

**Comment by Karmaknight421** [comment] 2023-11-23 20:20
I'll try moving my character to a new spot and restarting the server, I believe I had tried that before and still had the same issue but I could be wrong.

**Comment by StalkR** [comment] 2023-11-23 20:53
no need to restart the server, just the client - if it's the bug I suspect (#3) it's a bug in the client-side mod, losing track of objects

You can also find me on discord (torch, keen, etc), same username

**Comment by StalkR** [comment] 2024-01-02 08:08
closing this but let me know if you still have issues

**Closed as completed by StalkR** 2024-01-02 08:08 UTC
